### PR TITLE
intersect multiple arrays

### PR DESCRIPTION
**Pull request by dominictarr**
Intersect many arrays, using an algorithm similar to used in `big`.

If you pass in an array of arrays, instead of two arrays,
the intersection of all of those arrays will be returned.

I am using this in mynosql.

### CODE REVIEW

**Comment by dominictarr** [comment]
updated to add documentation

**Comment by juliangruber** [comment]
the idea, api and implementation lgtm, @minuteman3 what do you think?
also, should we support `intersect(a, b, c)` as well, for consistency?
@dominictarr did you try implementing this recursively, eg `intersect([a, b, c]) == intersect(intersect(a, b), c)`

**Comment by dominictarr** [comment]
Of course a recursive implementation would be entirely correct, but it seemed that using the `big` algorithm would be more performant if you do not throw away the object, create an array and start over each time.

@juliangruber usually, when you have more than 2 things, you already have them in an array, and to work with them you need to get them into an array, which just means `fn.apply(null, myArray)` and then `var ary = [].slice.call(arguments)` which is clutter at best and extra de-perf at worst.

**Comment by juliangruber** [comment]
ok!

**Comment by juliangruber** [comment]
published as 1.0.0 (finally)

**Comment by dominictarr** [comment]
sweet, thanks!

**Pull request merged**
